Traceback (most recent call last):
  File "train.py", line 100, in <module>
    model([map2angle(X), Ri, Ro])
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/xzcaplcu/repo/qtrkx-gnn-tracking/qnetworks/QGNN.py", line 279, in call
    e = self.EdgeNet(H, Ri, Ro)
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/xzcaplcu/repo/qtrkx-gnn-tracking/qnetworks/QGNN.py", line 114, in call
    exps = self.exp_layer(
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow_quantum/python/layers/circuit_executors/expectation.py", line 295, in call
    return self._expectation_op(inputs, symbol_names, symbol_values,
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow/python/ops/custom_gradient.py", line 264, in __call__
    return self._d(self._f, a, k)
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow/python/ops/custom_gradient.py", line 218, in decorated
    return _eager_mode_decorator(wrapped, args, kwargs)
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow/python/ops/custom_gradient.py", line 412, in _eager_mode_decorator
    result, grad_fn = f(*args, **kwargs)
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow_quantum/python/differentiators/differentiator.py", line 127, in op_wrapper_analytic
    forward_pass_vals = analytic_op(programs, symbol_names,
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow_quantum/core/ops/circuit_execution_ops.py", line 132, in <lambda>
    op(programs, symbol_names, symbol_values, pauli_sums)
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow_quantum/core/ops/tfq_simulate_ops.py", line 44, in tfq_simulate_expectation
    return SIM_OP_MODULE.tfq_simulate_expectation(
  File "<string>", line 46, in tfq_simulate_expectation
  File "/home/xzcaplcu/.conda/envs/qtrkx/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found a Pauli sum operating on qubits not found in circuit. [Op:TfqSimulateExpectation]
srun: error: compute-0-1: task 0: Exited with exit code 1
